"""empty message

Revision ID: cdbd354e15f4
Revises: 4511937f755f
Create Date: 2025-05-25 12:10:10.902856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbd354e15f4'
down_revision = '4511937f755f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('planet_specie',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('planet_specie',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
